CREATE TABLE IF NOT EXISTS DOMAIN.exchange_rate (
    id UUID PRIMARY KEY,
    currency_code VARCHAR(10) NOT NULL UNIQUE,
    currency_name_zh VARCHAR(100) NOT NULL UNIQUE,
    currency_symbol VARCHAR(10) NOT NULL UNIQUE,
    rate DECIMAL(18,6) NOT NULL,
    description VARCHAR(100),
    rate_time TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);